services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops_pipeline
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
      dvc remote add -d -f dagshub $${DAGSHUB_REPO_URL}.dvc &&

      dvc remote modify dagshub auth basic --local &&
      dvc remote modify dagshub user $${DAGSHUB_USERNAME} --local &&
      dvc remote modify dagshub password $${DAGSHUB_TOKEN} --local &&

      dvc repro &&
      dvc push
      "

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops_api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload