services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops_pipeline
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
      dvc remote add -d -f dagshub $${DAGSHUB_REPO_URL}.dvc &&

      dvc remote modify dagshub auth basic --local &&
      dvc remote modify dagshub user $${DAGSHUB_USERNAME} --local &&
      dvc remote modify dagshub password $${DAGSHUB_TOKEN} --local &&

      dvc repro &&
      dvc push
      "